// generated file
package haxe.ui.styles;

enum StyleBorderType {
    None;
    Full;
    Compound;
}

extern class Style {
    public function new(?left:Null<Float>, ?top:Null<Float>, ?autoWidth:Null<Bool>, ?width:Null<Float>, ?percentWidth:Null<Float>, ?minWidth:Null<Float>, ?minPercentWidth:Null<Float>, ?maxWidth:Null<Float>, ?maxPercentWidth:Null<Float>, ?initialWidth:Null<Float>, ?initialPercentWidth:Null<Float>, ?autoHeight:Null<Bool>, ?height:Null<Float>, ?percentHeight:Null<Float>, ?minHeight:Null<Float>, ?minPercentHeight:Null<Float>, ?maxHeight:Null<Float>, ?maxPercentHeight:Null<Float>, ?initialHeight:Null<Float>, ?initialPercentHeight:Null<Float>, ?padding:Null<Float>, ?paddingTop:Null<Float>, ?paddingLeft:Null<Float>, ?paddingRight:Null<Float>, ?paddingBottom:Null<Float>, ?marginTop:Null<Float>, ?marginLeft:Null<Float>, ?marginRight:Null<Float>, ?marginBottom:Null<Float>, ?horizontalSpacing:Null<Float>, ?verticalSpacing:Null<Float>, ?color:Null<Int>, ?backgroundColor:Null<Int>, ?backgroundOpacity:Null<Float>, ?backgroundColorEnd:Null<Int>, ?backgroundGradientStyle:Null<String>, ?backgroundImage:Null<haxe.ui.util.Variant>, ?backgroundImageRepeat:Null<String>, ?backgroundPositionX:Null<Float>, ?backgroundPositionY:Null<Float>, ?backgroundImageClipTop:Null<Float>, ?backgroundImageClipLeft:Null<Float>, ?backgroundImageClipBottom:Null<Float>, ?backgroundImageClipRight:Null<Float>, ?backgroundImageSliceTop:Null<Float>, ?backgroundImageSliceLeft:Null<Float>, ?backgroundImageSliceBottom:Null<Float>, ?backgroundImageSliceRight:Null<Float>, ?borderColor:Null<Int>, ?borderTopColor:Null<Int>, ?borderLeftColor:Null<Int>, ?borderBottomColor:Null<Int>, ?borderRightColor:Null<Int>, ?borderSize:Null<Float>, ?borderTopSize:Null<Float>, ?borderLeftSize:Null<Float>, ?borderBottomSize:Null<Float>, ?borderRightSize:Null<Float>, ?borderRadius:Null<Float>, ?borderRadiusTopLeft:Null<Float>, ?borderRadiusTopRight:Null<Float>, ?borderRadiusBottomLeft:Null<Float>, ?borderRadiusBottomRight:Null<Float>, ?borderOpacity:Null<Float>, ?borderStyle:Null<String>, ?icon:Null<haxe.ui.util.Variant>, ?iconPosition:Null<String>, ?horizontalAlign:Null<String>, ?verticalAlign:Null<String>, ?textAlign:Null<String>, ?opacity:Null<Float>, ?clip:Null<Bool>, ?native:Null<Bool>, ?fontName:Null<String>, ?fontSize:Null<Float>, ?fontBold:Null<Bool>, ?fontUnderline:Null<Bool>, ?fontItalic:Null<Bool>, ?fontStrikeThrough:Null<Bool>, ?cursor:Null<String>, ?cursorOffsetX:Null<Int>, ?cursorOffsetY:Null<Int>, ?hidden:Null<Bool>, ?filter:Null<Array<haxe.ui.filters.Filter>>, ?backdropFilter:Null<Array<haxe.ui.filters.Filter>>, ?resource:Null<haxe.ui.util.Variant>, ?animationName:Null<String>, ?animationOptions:Null<haxe.ui.styles.animation.Animation.AnimationOptions>, ?mode:Null<String>, ?pointerEvents:Null<String>, ?contentType:Null<String>, ?direction:Null<String>, ?contentWidth:Null<Float>, ?contentWidthPercent:Null<Float>, ?contentHeight:Null<Float>, ?contentHeightPercent:Null<Float>, ?wordWrap:Null<Bool>, ?imageRendering:Null<String>, ?backgroundWidth:Null<Float>, ?backgroundWidthPercent:Null<Float>, ?backgroundHeight:Null<Float>, ?backgroundHeightPercent:Null<Float>, ?layout:Null<String>, ?includeInLayout:Null<Bool>, ?justifyContent:Null<String>, ?borderType:Null<haxe.ui.styles.StyleBorderType>, ?hasBorder:Null<Bool>, ?fullBorderSize:Null<Float>):Void;
    public var left:Null<Float>;
    public var top:Null<Float>;
    public var autoWidth:Null<Bool>;
    public var width:Null<Float>;
    public var percentWidth:Null<Float>;
    public var minWidth:Null<Float>;
    public var minPercentWidth:Null<Float>;
    public var maxWidth:Null<Float>;
    public var maxPercentWidth:Null<Float>;
    public var initialWidth:Null<Float>;
    public var initialPercentWidth:Null<Float>;
    public var autoHeight:Null<Bool>;
    public var height:Null<Float>;
    public var percentHeight:Null<Float>;
    public var minHeight:Null<Float>;
    public var minPercentHeight:Null<Float>;
    public var maxHeight:Null<Float>;
    public var maxPercentHeight:Null<Float>;
    public var initialHeight:Null<Float>;
    public var initialPercentHeight:Null<Float>;
    public var padding(get, set):Null<Float>;
    public var paddingTop:Null<Float>;
    public var paddingLeft:Null<Float>;
    public var paddingRight:Null<Float>;
    public var paddingBottom:Null<Float>;
    private function set_padding(value:Null<Float>):Null<Float>;
    public var marginTop:Null<Float>;
    public var marginLeft:Null<Float>;
    public var marginRight:Null<Float>;
    public var marginBottom:Null<Float>;
    public var horizontalSpacing:Null<Float>;
    public var verticalSpacing:Null<Float>;
    public var color:Null<Int>;
    public var backgroundColor:Null<Int>;
    public var backgroundOpacity:Null<Float>;
    public var backgroundColorEnd:Null<Int>;
    public var backgroundGradientStyle:Null<String>;
    public var backgroundImage:haxe.ui.util.Variant;
    public var backgroundImageRepeat:Null<String>;
    public var backgroundPositionX:Null<Float>;
    public var backgroundPositionY:Null<Float>;
    public var backgroundImageClipTop:Null<Float>;
    public var backgroundImageClipLeft:Null<Float>;
    public var backgroundImageClipBottom:Null<Float>;
    public var backgroundImageClipRight:Null<Float>;
    public var backgroundImageSliceTop:Null<Float>;
    public var backgroundImageSliceLeft:Null<Float>;
    public var backgroundImageSliceBottom:Null<Float>;
    public var backgroundImageSliceRight:Null<Float>;
    public var borderColor:Null<Int>;
    public var borderTopColor:Null<Int>;
    public var borderLeftColor:Null<Int>;
    public var borderBottomColor:Null<Int>;
    public var borderRightColor:Null<Int>;
    public var borderSize:Null<Float>;
    public var borderTopSize:Null<Float>;
    public var borderLeftSize:Null<Float>;
    public var borderBottomSize:Null<Float>;
    public var borderRightSize:Null<Float>;
    public var borderRadius:Null<Float>;
    public var borderRadiusTopLeft:Null<Float>;
    public var borderRadiusTopRight:Null<Float>;
    public var borderRadiusBottomLeft:Null<Float>;
    public var borderRadiusBottomRight:Null<Float>;
    public var borderOpacity:Null<Float>;
    public var borderStyle:Null<String>;
    public var icon:haxe.ui.util.Variant;
    public var iconPosition:Null<String>;
    public var horizontalAlign:Null<String>;
    public var verticalAlign:Null<String>;
    public var textAlign:Null<String>;
    public var opacity:Null<Float>;
    public var clip:Null<Bool>;
    public var native:Null<Bool>;
    public var fontName:Null<String>;
    public var fontSize:Null<Float>;
    public var fontBold:Null<Bool>;
    public var fontUnderline:Null<Bool>;
    public var fontItalic:Null<Bool>;
    public var fontStrikeThrough:Null<Bool>;
    public var cursor:Null<String>;
    public var cursorOffsetX:Null<Int>;
    public var cursorOffsetY:Null<Int>;
    public var hidden:Null<Bool>;
    public var filter:Array<haxe.ui.filters.Filter>;
    public var backdropFilter:Array<haxe.ui.filters.Filter>;
    public var resource:haxe.ui.util.Variant;
    public var animationName:Null<String>;
    public var animationOptions:haxe.ui.styles.animation.Animation.AnimationOptions;
    public var mode:String;
    public var pointerEvents:String;
    public var contentType:String;
    public var direction:String;
    public var contentWidth:Null<Float>;
    public var contentWidthPercent:Null<Float>;
    public var contentHeight:Null<Float>;
    public var contentHeightPercent:Null<Float>;
    public var wordWrap:Null<Bool>;
    public var imageRendering:String;
    public var backgroundWidth:Null<Float>;
    public var backgroundWidthPercent:Null<Float>;
    public var backgroundHeight:Null<Float>;
    public var backgroundHeightPercent:Null<Float>;
    public var layout:String;
    public var includeInLayout:Null<Bool>;
    public var justifyContent:String;
    public var borderType(get, null):haxe.ui.styles.StyleBorderType;
    private function get_borderType():haxe.ui.styles.StyleBorderType;
    public var hasBorder(get, null):Bool;
    private function get_hasBorder():Bool;
    public var fullBorderSize(get, null):Null<Float>;
    private function get_fullBorderSize():Null<Float>;
    public function mergeDirectives(map:Map<String, haxe.ui.styles.elements.Directive>):Void;
    public function apply(s:haxe.ui.styles.Style):Void;
    public function equalTo(s:haxe.ui.styles.Style):Bool;
    private function createAnimationOptions():Void;
    private function parseFilter(value:haxe.ui.styles.Value, filters:Array<haxe.ui.filters.Filter>):Array<haxe.ui.filters.Filter>;
    public function clone():haxe.ui.styles.Style;
}

